In [7]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

In [16]:
data01=pd.read_excel("EMPIR_PhotoLED_SPECTRAL_DATABASE_version_2.xlsx",sheet_name="DATA")

In [17]:
data01.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478 entries, 0 to 477
Columns: 1495 entries, CCT / K (min Duv) to 1329594372375
dtypes: object(1495)
memory usage: 5.5+ MB


In [18]:
data01


CCT / K (min Duv) 1705.35231381655 1713.38753774762  \
0    CCT / K (MacCamy, not precise)      1736.929722      1746.038149   
1                                Rf        52.026891        53.393764   
2                                Ra        36.854868        58.611153   
3                                R9      -111.405013       -44.358968   
4                               Duv         0.003889         0.005259   
..                              ...              ...              ...   
473                             826                0                0   
474                             827                0                0   
475                             828                0                0   
476                             829                0                0   
477                             830                0                0   

    1723.05780276656 1999.70770440996 2000.43594930321 2001.59848388284  \
0         1751.22689      1981.136046      1981.914894      1983.029601   
1          59.853801        84.155885        84.207529        84.198936   
2          48.940549        79.737989        79.648359        79.812248   
3         -67.801535        67.036213         66.14593        67.337749   
4           0.004458         0.000061         0.000092         0.000089   
..               ...              ...              ...              ...   
473         0.000428         0.000056         0.000012         0.000038   
474         0.000404         0.000052         0.000026         0.000046   
475          0.00043         0.000053         0.000028         0.000044   
476         0.000398         0.000043         0.000024          0.00004   
477         0.000383          0.00007        -0.000003         0.000051   

    2016.09058864415 2397.80642092228 2457.84346759319  ... 13670.8092689514  \
0        1999.778316      2376.050078      2455.602571  ...     13012.461169   
1          87.569156        81.712481        66.934518  ...        58.705618   
2          89.797702        90.730333        61.378274  ...        68.566726   
3          47.532339        77.231185       -53.655122  ...        33.632819   
4           0.001192        -0.005547         0.007993  ...        -0.019937   
..               ...              ...              ...  ...              ...   
473         0.000332                0                0  ...                0   
474         0.000336                0                0  ...                0   
475         0.000332                0                0  ...                0   
476         0.000314                0                0  ...                0   
477         0.000306                0                0  ...                0   

    17404.1390419006 20704.7872394323 24579.2350769043 26462.1472358704  \
0       15741.675721      17903.54316     19995.199607     20786.818858   
1          61.719455        69.460104        64.792171                0   
2          69.854846        74.343482        77.757632                0   
3          39.730473        49.190597         75.67656                0   
4           -0.01776        -0.024162        -0.024556        -0.022279   
..               ...              ...              ...              ...   
473                0                0                0                0   
474                0                0                0                0   
475                0                0                0                0   
476                0                0                0                0   
477                0                0                0                0   

    95088.9239162207 49870.399476029 124156.799213961 796918788804.688  \
0       26596.409443    28058.356625     31681.715633     37217.402786   
1                  0               0                0                0   
2                  0               0                0                0   
3                  0               0                0                0   
4       

In [25]:
data02 = data01.drop(labels=None,axis=0, index=[0,1,2,3,4,5,6], columns=None, inplace=False)
data02

CCT / K (min Duv) 1705.35231381655 1713.38753774762 1723.05780276656  \
7                 360         0.000023         0.000034                0   
8                 361          0.00002         0.000024                0   
9                 362         0.000024         0.000028                0   
10                363         0.000015         0.000028                0   
11                364         0.000027          0.00003                0   
..                ...              ...              ...              ...   
473               826                0                0         0.000428   
474               827                0                0         0.000404   
475               828                0                0          0.00043   
476               829                0                0         0.000398   
477               830                0                0         0.000383   

    1999.70770440996 2000.43594930321 2001.59848388284 2016.09058864415  \
7           0.000088         0.000026         0.000054         0.000085   
8           0.000074         0.000014         0.000067         0.000098   
9           0.000075         0.000023         0.000041         0.000089   
10          0.000051         0.000032         0.000038         0.000067   
11          0.000073         0.000004         0.000051         0.000073   
..               ...              ...              ...              ...   
473         0.000056         0.000012         0.000038         0.000332   
474         0.000052         0.000026         0.000046         0.000336   
475         0.000053         0.000028         0.000044         0.000332   
476         0.000043         0.000024          0.00004         0.000314   
477          0.00007        -0.000003         0.000051         0.000306   

    2397.80642092228 2457.84346759319  ... 13670.8092689514 17404.1390419006  \
7                  0                0  ...         0.000138         0.000577   
8                  0                0  ...         0.000119         0.000556   
9                  0                0  ...         0.000141         0.000395   
10                 0                0  ...         0.000165         0.000531   
11                 0                0  ...         0.000138         0.000462   
..               ...              ...  ...              ...              ...   
473                0                0  ...                0                0   
474                0                0  ...                0                0   
475                0                0  ...                0                0   
476                0                0  ...                0                0   
477                0                0  ...                0                0   

    20704.7872394323 24579.2350769043 26462.1472358704 95088.9239162207  \
7           0.000117                0          0.00017         0.000087   
8           0.000049                0         0.000115         0.000128   
9           0.000047                0         0.000061         0.000082   
10          0.000095                0         0.000077         0.000086   
11          0.000082                0         0.000102         0.000103   
..               ...              ...              ...              ...   
473                0                0                0                0   
474                0                0                0                0   
475                0                0                0                0   
476                0                0                0                0   
477                0                0                0                0   

    49870.399476029 124156.799213961 796918788804.688 1329594372375  
7                 0                0                0     -0.000001  
8          0.000621             -0.0                0     -0.000001  
9          0.000594                0                0     -0.000001  
10          0.00055             -0.0            

In [26]:
data02.drop(['CCT / K (min Duv)'],axis=1)


1.705352e+03 1.713388e+03 1.723058e+03 1.999708e+03 2.000436e+03  \
7       0.000023     0.000034            0     0.000088     0.000026   
8        0.00002     0.000024            0     0.000074     0.000014   
9       0.000024     0.000028            0     0.000075     0.000023   
10      0.000015     0.000028            0     0.000051     0.000032   
11      0.000027      0.00003            0     0.000073     0.000004   
..           ...          ...          ...          ...          ...   
473            0            0     0.000428     0.000056     0.000012   
474            0            0     0.000404     0.000052     0.000026   
475            0            0      0.00043     0.000053     0.000028   
476            0            0     0.000398     0.000043     0.000024   
477            0            0     0.000383      0.00007    -0.000003   

    2.001598e+03 2.016091e+03 2.397806e+03 2.457843e+03 2.479435e+03  ...  \
7       0.000054     0.000085            0            0            0  ...   
8       0.000067     0.000098            0            0            0  ...   
9       0.000041     0.000089            0            0            0  ...   
10      0.000038     0.000067            0            0            0  ...   
11      0.000051     0.000073            0            0            0  ...   
..           ...          ...          ...          ...          ...  ...   
473     0.000038     0.000332            0            0     0.000117  ...   
474     0.000046     0.000336            0            0     0.000113  ...   
475     0.000044     0.000332            0            0     0.000108  ...   
476      0.00004     0.000314            0            0     0.000104  ...   
477     0.000051     0.000306            0            0     0.000098  ...   

    1.367081e+04 1.740414e+04 2.070479e+04 2.457924e+04 2.646215e+04  \
7       0.000138     0.000577     0.000117            0      0.00017   
8       0.000119     0.000556     0.000049            0     0.000115   
9       0.000141     0.000395     0.000047            0     0.000061   
10      0.000165     0.000531     0.000095            0     0.000077   
11      0.000138     0.000462     0.000082            0     0.000102   
..           ...          ...          ...          ...          ...   
473            0            0            0            0            0   
474            0            0            0            0            0   
475            0            0            0            0            0   
476            0            0            0            0            0   
477            0            0            0            0            0   

    9.508892e+04 4.987040e+04 1.241568e+05 7.969188e+11 1.329594e+12  
7       0.000087            0            0            0    -0.000001  
8       0.000128     0.000621         -0.0            0    -0.000001  
9       0.000082     0.000594            0            0    -0.000001  
10      0.000086      0.00055         -0.0            0    -0.000001  
11      0.000103      0.00056            0            0            0  
..           ...          ...          ...          ...          ...  
473            0            0            0            0            0  
474            0            0            0            0            0  
475            0            0            0            0            0  
476            0            0            0            0            0  
477            0            0            0            0            0  

[471 rows x 1494 columns]

In [29]:
data = data02.values
print(data)

[[360 2.2757918125842892e-05 3.399140921248083e-05 ... 0 0
  -1.4641251332350348e-06]
 [361 1.9919133402337825e-05 2.3700268496282506e-05 ...
  -2.3619574765657763e-07 0 -7.864368065780602e-07]
 [362 2.426599233262612e-05 2.7677856950898395e-05 ... 0 0
  -1.4641251332350348e-06]
 ...
 [828 0 0 ... 0 0 0]
 [829 0 0 ... 0 0 0]
 [830 0 0 ... 0 0 0]]


In [31]:
data.shape

(471, 1495)

In [32]:
data02.to_csv("data")

In [34]:
data02.to_excel('data')

ValueError: No engine for filetype: ''

In [38]:
data.shape

(471, 1495)